# Generated by Django 3.2 on 2022-12-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomment',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
