# Generated by Django 3.2 on 2022-12-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20221205_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomment',
            name='content',
            field=models.TextField(max_length=150, verbose_name='대댓글'),
        ),
    ]
